name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:

  checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Static checks
        run: |
          bash -xc "shellcheck */*.sh"
          bash -xc "find */ -name '*.sh' | xargs -I {} test -x {}"

      - name: Tests
        run: |
          bash -xc "tests/*.sh"
