name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:

  checks:

    runs-on: ubuntu-latest

    services:
      mock-registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Static checks
        run: |
          bash -xc "shellcheck */*.sh"
          bash -xc "find */ -name '*.sh' | xargs -I {} test -x {}"

      - name: Tests
        run: |
          npm install bats
          node_modules/bats/bin/bats -r tests/
        env:
          DOCKER_REGISTRY: "localhost:5000/"
          DOCKER_USERNAME: "foo"
          DOCKER_PASSWORD: "bar"
          